### ISSUE TITLE
[Error] An error occurred when executing the check FREECAM

### ISSUE THREAD

**Issue by Nety01** [CraftG/Horizon#113]
Please describe the problem in detail and provide as much information as possible.

Horizon Version: 1.4.6-Hotfix#8

Server Core: Paper

Server version: 1.13.2

Server Log: [11:51:33] [Server thread/INFO]: (H-INFO) | Enabling checks...
[11:51:33] [Horizon Processing Thread/WARN]: xyz.hstudio.horizon.i.iiIiiIiIIi: An error occurred when executing the check FREECAM
[11:51:33] [Horizon Processing Thread/WARN]: at xyz.hstudio.horizon.n.s.IiIIIIiiII.😂😅(bf:77)
[11:51:33] [Horizon Processing Thread/WARN]: at xyz.hstudio.horizon.g.IIIiiiIiIi.run(ra:115)
[11:51:33] [Horizon Processing Thread/WARN]: at java.util.TimerThread.mainLoop(Timer.java:555)
[11:51:33] [Horizon Processing Thread/WARN]: at java.util.TimerThread.run(Timer.java:505)
[11:51:33] [Horizon Processing Thread/WARN]: Caused by: java.lang.NullPointerException
[11:51:33] [Horizon Processing Thread/WARN]: at xyz.hstudio.horizon.n.s.IiIIIIiiII.😂😅(bf:66)
[11:51:33] [Horizon Processing Thread/WARN]: ... 3 more

Additional Info: It appeared on server start

**Comment by CraftG** [comment]
Fixed in dev build.
