### ISSUE TITLE
1.15 NullPointerException on load

### ISSUE THREAD

**Issue by TakoidGit** [CraftG/Horizon#18]
Please describe the problem in detail and provide as much information as possible.

INFOMATION:
Server: PaperSpigot
Server version: 1.13.2

bypass/false positive/bug/error/suggestion
ISSUE TYPE: Error

If reporting a console error.
SERVER LOG: ` [14:38:48 ERROR]: Error occurred while enabling Horizon v1.1.5 (Is it up to date?)
java.lang.NullPointerException: null
        at xyz.hstudio.horizon.config.Config.‎　‎　꧅(cb:146) ~[?:?]
        at xyz.hstudio.horizon.check.Check.<init>(rc:21) ~[?:?]
        at xyz.hstudio.horizon.check.w.iIiiIIIIiI.<init>(lc:153) ~[?:?]
        at xyz.hstudio.horizon.Horizon.‎　꧅‎　(yj:164) ~[?:?]
        at xyz.hstudio.horizon.Horizon.onEnable(yj:80) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-625]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-625]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-625]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-625]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-625]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-625]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-625]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-625]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-625]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-625]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211] `

**Comment by Blamo27** [comment]
@TakoidGit What is your ProtocolLib version ?

**Comment by CraftG** [comment]
Please delete the old config file.
