### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by Fundryi** [CraftG/Horizon#39]
Please describe the problem in detail and provide as much information as possible.

INFOMATION:
Server: (PaperSpigot/ aka FoxSpigot)
Server version: 1.8

bypass/false positive/bug/error/suggestion
ISSUE TYPE: error

If reporting a console error.
SERVER LOG: 
`
Error occurred while enabling Horizon v1.3.3 (Is it up to date?)
java.lang.NullPointerException
at xyz.hstudio.horizon.check.Check.<init>(mc:50) ~[?:?]
at xyz.hstudio.horizon.check.z.iiIIIiiIIi.<init>(yg:113) ~[?:?]
at xyz.hstudio.horizon.check.CheckManager.‎　‎　꧅‎　(pn:78) ~[?:?]
at xyz.hstudio.horizon.Horizon.onEnable(hn:174) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[FoxSpigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [FoxSpigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [FoxSpigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:365) [FoxSpigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:324) [FoxSpigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [FoxSpigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [FoxSpigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [FoxSpigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:271) [FoxSpigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [FoxSpigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[15:54:41 INFO]: [Horizon] Disabling Horizon v1.3.3
`

If reporting a false positive.
HORIZON LOG: -

If reporting a false positive/bypass. (If possible)
VIDEO: -

If reporting a bypass.
CLIENT:-

Regards

**Comment by CraftG** [comment]
please delete the old config.yml
