### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by muddup** [CraftG/Horizon#8]
Please describe the problem in detail and provide as much information as possible.

INFOMATION:
Server: git-Paper-597
Server version: 1.13.2

bypass/false positive/bug/error/suggestion
ISSUE TYPE: error

If reporting a console error.
SERVER LOG:  
Error occurred while enabling Horizon v1.0.5-BETA (Is it up to date?)
java.lang.NullPointerException: null
	at xyz.hstudio.horizon.checks.Check.<init>(Unknown Source) ~[?:?]
	at xyz.hstudio.horizon.checks.z.?.<init>(Unknown Source) ~[?:?]
	at xyz.hstudio.horizon.Horizon.onEnable(Unknown Source) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-597]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-597]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-597]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-597]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-597]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[20:33:13] [Server thread/INFO]: [Horizon] Disabling Horizon v1.0.5-BETA

If reporting a false positive.
HORIZON LOG: 

If reporting a false positive/bypass. (If possible)
VIDEO: 

If reporting a bypass.
CLIENT:

**Comment by muddup** [comment]
Horizon 1.0.4-BETA* runs great with no errors.

**Comment by CraftG** [comment]
please delete the config.yml in the plugin folder.

**Comment by muddup** [comment]
Thanks.
